config/routes.rb
Rails.application.routes.draw do
  get 'contests/show'

  # Devise routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  # ActiveAdmin routes
  ActiveAdmin.routes(self)



  # Resource routes


  resources :campaign_finance_modules
  resources :candidate_committees do
    resources :reports
  end
  resources :candidates
  resources :former_offices
  resources :registration_snapshots do
    collection { post :import }
  end
  resources :statistical_data
  resources :historical_candidates
  resources :election_histories
  resources :updates
  
  resources :people do 
    resources :reports, only: [:index]
    
    member do
      get 'archive'
    end
  
    collection do
      get 'search'
    end
  end
  
  resources :campaigns
  resources :campaign_candidates
  resources :pricing, only: [:index]
  resources :reports
  resources :districts do
    member do
      get :follow
      get :unfollow
    end
    collection { post :import }
  end
  resources :jurisdictions do
    member do
      patch :toggle_archive
    end
  end
  resources :subscriptions
  resources :dashboard
  resources :help
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :users, only: [:index, :destroy]
  resources :blog_posts
  get 'tags/:tag_name', to: 'blog_posts#index', as: :filter_by_tag
  get 'navigate_jurisdiction', to: 'jurisdictions#navigate', as: :navigate_jurisdiction
  resources :elections, param: :slug do
    member do
      post 'process_results_update'
    end
    
    resources :election_updates
    resources :contests, only: [:show] do
      member do
        post 'pin', to: 'pinned_contests#create'
        delete 'unpin', to: 'pinned_contests#destroy'
      end
    end
    resources :uploads, only: [:create]
  end

  



  # Custom routes
  get 'emails/unsubscribe'
  get :search, controller: :main
  match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user

  # Root path
  root 'pages#home'

  # Additional information
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_at_large_incumbent.html.erb
        <div class="col-sm-3 my-auto"  >
          <% if person.image.present? %>
          <%= image_tag person.image.url(:headshot), alt: 'headshot', :class => " center-image avatar img-fluid shadow", size: "200x200"  %><br>
          <% else %>
          <%= image_tag 'https://nex3.com/wp-content/uploads/2019/12/placeholder-headshot-300x300.png', alt: 'vacant_headshot', :class => "avatar text-center mb-3 shadow", size: "200x200"  %></div><br>
          <%end%>     
        </div>
        <div class="col-md m-1 px-2">
            <div class="row">
              <div class="col-md-9"> <h1 class=" primary-blue text-center text-md-left"><strong><%= link_to "#{person.first_name} #{person.last_name} #{person.party_abbreviation}", person %></strong></h1></div>
              
              <div class="col-md text-center text-md-right">

              <% if user_signed_in? && current_user.admin? %>    
                <%= link_to "Edit", edit_person_path(person), :class => "btn btn-sm btn-primary text-md-right my-auto" %>
              <%end%>

              <%if person.twitter.present? %>
                  <%= link_to "https://www.twitter.com/" + person.twitter, target: :_blank, :class => "nounderline text-md-right px-1", aria: { label: 'View Twitter Page' }   do %>
                      <%= fa_icon "twitter" %>
                  <% end %>
              <%end%>
              
              <% if person.facebook.present? %>
                <%= link_to "https://www.facebook.com/" + person.facebook, target: :_blank, :class => "nounderline text-md-right px-1", aria: { label: 'View Facebook Page' }   do %>
                    <%= fa_icon "facebook" %>
                <% end %>
              <%end%> 

              <% if person.linkedin_url.present? %>
                <%= link_to "#{person.linkedin_url}", target: :_blank, :class => "nounderline px-1 text-md-right", aria: { label: 'View LinkedIn Profile' }   do %>
                    <%= fa_icon "linkedin" %>
                <% end %>
              <%end%>               
              
              </div>
            </div>
           
              <% if person.district.present? %>
              <h5 class="text-center text-md-left"><%= link_to "#{person.district.jurisdiction.name}", person.district.jurisdiction, :class => "nounderline" %> - 
                <% if person.incumbent_district.district != "At Large" && person.incumbent_district.is_seat == false && person.incumbent_district.is_area == false %>
                <%= link_to "#{person.district.district_title}, #{person.incumbent_district.district.to_i.ordinalize} District", person.incumbent_district, :class => "nounderline" %> 
                <% elsif person.incumbent_district.is_seat %>
                <%= link_to "#{person.district.district_title}, Seat #{person.incumbent_district.district}", person.incumbent_district, :class => "nounderline" %>
                <% elsif person.incumbent_district.is_area %>
                <%= link_to "#{person.district.district_title}, Trustee Area #{person.incumbent_district.district}", person.incumbent_district, :class => "nounderline" %>
                <% elsif person.incumbent_district.district == "At Large" %>
                <%= link_to "#{person.district.district_title}", person.incumbent_district, :class => "nounderline" %>
                <%end%></h5>
              <%end%>
              
              <div class="row text-center text-md-left mb-1 pl-2">
              <table class="table borderless table-sm">
                
                <% if person.is_candidate == true %>
                <tr>
                  <td class="heavy">Candidate for:</td>
                  <td>
                    <%= link_to "#{person.campaign.district.full_district_name}", person.campaign.district %>
                  </td>
                </tr>
                <%end%>
                <% if person.former_offices.present? && person.district.nil? %>
                <tr>
                  <td class="heavy">Formerly Represented:</td>
                  <td>
                    <%= link_to "#{person.former_offices.order("end_year desc").first.district.full_district_name}", person.former_offices.order("end_year desc").first.district %>
                  </td>
                </tr>
                <%end%>

                <tr>
                  <td class="heavy col-4">Birthdate:</td>
                  <td><%if person.birthdate.present? %><%= person.birthdate.to_formatted_s(:long) %> (Age <%= person.calculated_age %>)<%else%><em>Unknown</em><%end%></td>
                </tr>

                <% if person.district.present?%>
                  <tr>
                  <td class="heavy col-4">Term Expires:</td>
                  <td><%= person.district.term_expires %> <%if person.term? %><%= "(Term Limited in #{person.term})" %><%end%></td>
                  </tr>
                <%end%>

                <%if person.resides_in_present %>
                  <tr>
                    <td class="heavy col-4">Resides in:</td>
                    <td><% if person.congressional_district != nil %>
                    <%=  "CD-#{person.congressional_district}" %>,
                    <%end%>
                    <% if person.senate_district != nil %>
                    <%= "SD-#{person.senate_district}" %>,
                    <%end%>
                    <% if person.assembly_district != nil %>
                    <%= "AD-#{person.assembly_district}" %>,
                    <%end%>
                    <% if person.supe_district != nil %>
                    <%= "BOS-#{person.supe_district}" %>
                    <%end%></td>
                  </tr>
                <%end%>

                <% if person.official_website.present? || person.email.present? %>
                  <tr>
                    <td class="heavy col-4">Official Contact Info:</td>
                    <td>

                      <%if person.email.present?%>
                        <%= link_to "Website", person.campaign_website, target: :_blank %>
                      <%end%>

                      <% if person.official_website.present? && person.email.present? %>
                       | 
                      <%end%>

                       <%if person.email.present?%>
                        <%= mail_to person.email, "E-Mail", target: :_blank %>
                      <%end%>


                    
                    </td>
                  </tr>
                <%end %>
              </table>      
              </div> 
      </div>
      <div class="row px-3">
        <div class="col">
        <!--Start of Biography Section-->

        <% if person.bio.present? %>
        <strong>Biography:</strong>
        <div>    
          <% if person.bio.length > 300 %>
          <%= truncate(person.bio, length: 300, :escape => false) %>
          <%= link_to 'Read more', '', class: "read-more-#{person.id}" %>
          <script>
          $('.read-more-<%= person.id %>').on('click', function(e) {
            e.preventDefault()
            $(this).parent().html('<%= escape_javascript h(person.bio).gsub(/\n/, '</br>').html_safe %>')
            })
          </script>
          <% else %>
            <%= h(person.bio).gsub(/\n/, '</br>').html_safe %>
          <% end %>
        </div>
        <%end%>

    </div>
</div>


      
      

app/views/shared/_candidates.html.erb
  <div class="card shadow-sm  bg-white rounded primary-border p-0">
    <div class="card-header d-flex justify-content-between align-items-center">
      <span>Campaign for <%= link_to district.full_district_name, district %>
        <% if user_signed_in? && current_user.admin? %>
          (<%= link_to "Edit Campaign", edit_campaign_path(campaign, :district_id => campaign.district.id) %>)
        <% end %>
      </span>
      <span class="text-right "><%= campaign.election_date.strftime("%B %d, %Y") %></span>
    </div>

    <div class="table-responsive">
      <table class="table table-sm  bg-white mb-0" style="width:100%">
        <thead>
          <tr>
            <th class="pb-2 text-nowrap "></th>
            <th class="text-nowrap">Candidate</th>
            <th class="text-end text-nowrap">Last Report</th>
            <th class="text-end text-nowrap">Total Raised</th>
            <th class="text-end text-nowrap">Total Spent</th>
            <th class="text-end  text-nowrap">Debt</th>
            <th class="text-end text-nowrap">Cash-on-Hand</th>
            <th class="text-end  text-nowrap pe-4">Net COH</th>
          </tr>
        </thead>
        <tbody>
          <% candidates.each do |candidate| %>
            <tr>
              <td class="pl-4 text-nowrap">
                <% if candidate.person.present? && candidate.person.image.present? %>
                  <%= image_tag candidate.person.image.url(:headshot), alt: 'headshot', class: "mx-auto my-auto d-block avatar shadow-sm", size: "50x50" %>
                <% else %>
                  <%= image_tag 'blank-headshot.png', alt: 'vacant_headshot', class: "mx-auto my-auto d-block avatar shadow-sm", size: "50x50" %>
                <%end %>
            </td>
          <td class="text-nowrap">
            <% party_abbr = party_abbreviation(candidate.party_registration) %>
            <% if candidate.person.present? %>
              <%= link_to "#{candidate.person.full_name}#{candidate.is_district_incumbent} (#{party_abbr})", candidate.person %>
            <% else %>
              <%= "#{candidate.first_name} #{candidate.last_name} (#{party_abbr})" %>
            <% end %>
            <br>
            <small><%= candidate.display_ballot_title %></small>
            <% if user_signed_in? && current_user.admin? %>
              <%= link_to "Remove", candidate, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>

          <%# Retrieve report data for the primary committee %>
          <% primary_committee = candidate.person&.candidate_committees&.find_by(primary_committee: true) %>
          <% reports = primary_committee&.reports %>

         <% if reports.present? %>
          <td class="text-end text-nowrap">
            <% latest_report = reports.order('period_end DESC').first %>
            <%= link_to latest_report.period_end.strftime("%m-%d-%y"), report_path(latest_report) %>
          </td>
          <td class="text-end "><%= number_to_currency(reports.sum(:period_receipts)) %></td>
          <td class="text-end"><%= number_to_currency(reports.sum(:period_disbursements)) %></td>
          <td class="text-end  "><%= number_to_currency(reports.order('period_end DESC').first.current_debt) %></td>
          <td class="text-end "><%= number_to_currency(reports.order('period_end DESC').first.current_coh) %></td>
          <td class="text-end  pe-4"><%= number_to_currency(reports.order('period_end DESC').first.net_coh) %></td>
        <% else %>
          <!-- Default values when no reports are present -->
          <td class="text-end text-nowrap">No Reports</td>
          <td class="text-end ">$0.00</td>
          <td class="text-end ">$0.00</td>
          <td class="text-end ">$0.00</td>
          <td class="text-end ">$0.00</td>
          <td class="text-end  pe-4">$0.00</td>
        <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="px-4 mb-2">
  <small class="text-muted">* = Incumbent(s)</small>
</div>
  </div>

app/views/shared/_historical_election.html.erb
<% historical_elections.each do |historical_campaign| %>
  <div class="card shadow-sm bg-white mb-3 rounded primary-border p-0">
    <div class="card-header">
      <% if show_district == true %>
        <%= "#{historical_campaign.district.full_district_name} | #{historical_campaign.election_date.strftime("%Y")} #{historical_campaign.election_type} Election Results" %> 
        <span class="font-weight-light"><%= "(#{historical_campaign.election_date.strftime("%B %e, %Y")})" %></span> 
        <% if user_signed_in? && current_user.admin? %> 
          - <%= link_to 'Edit', edit_campaign_path(historical_campaign, election_date: historical_campaign.election_date, district_id: historical_campaign.district_id) %>
        <% end %>
      <% else %>
        <%= "#{historical_campaign.election_date.strftime("%Y")} #{historical_campaign.election_type} Election Results" %> 
        <span class="font-weight-light"><%= "(#{historical_campaign.election_date.strftime("%B %e, %Y")})" %></span> 
        <% if user_signed_in? && current_user.admin? %> 
          - <%= link_to 'Edit', edit_campaign_path(historical_campaign, election_date: historical_campaign.election_date, district_id: historical_campaign.district_id) %>
        <% end %>
      <% end %>
    </div>
    <div class="table-responsive">
      <table class="table-sm table bg-white">
        <thead>
          <tr>
            <th style="width: 5%"></th>
            <th style="width: 30%">Name</th>
            <th style="width: 10%">Votes</th>
            <th style="width: 10%">Vote %</th>
            <th class="d-none d-md-table-cell" style="width: 50%">Vote Share</th>
          </tr>
        </thead>
        <tbody>
          <% historical_campaign.candidates.order('votes desc').each_with_index do |candidate, index| %>
            <tr>
              <td class="pl-4">
                <% if index <= candidate.campaign.number_of_winners - 1 %> 
                  &#10004; 
                <% end %>
              </td>
              <td>
                <% if candidate.person.present? && show_district %>
                  <%= link_to candidate.display_name, candidate.person %>
                <% elsif candidate.person.present? %>
                  <%= link_to candidate.display_name, candidate.person %>
                <% else %>
                  <%= candidate.display_name %>
                <% end %>
              </td>
              <td><%= number_with_delimiter(candidate.votes, delimiter: ',') %> </td>
              <td class="pe-4 font-weight-bold"><%= candidate.vote_share %></td>
              <td class="pe-4 d-none d-md-block">
                <% if candidate.campaign.election_date < Date.today %>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: <%= candidate.vote_share %>;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/shared/_incumbent.html.erb
  <div class="container">
  <div class="row ">

      <div class="rounded primary-border card p-0">
      <% if local_assigns[:show_header] %>
        <div class="card-header">
          <span>Incumbent</span>
        </div>
      <% end %>
        <div class="card-body text-center">
          <% if person.image.present? %>
            <%= image_tag person.image.url, alt: "#{person.first_name} #{person.last_name}", class: "img-fluid rounded-circle mb-4", style: "width: 250px; height: 250px; object-fit: cover; object-position: top;" %>
          <% else %>
            <%= image_tag 'blank-headshot.png', alt: 'Headshot placeholder', class: "img-fluid rounded-circle mb-4", style: "width: 250px; height: 250px; object-fit: cover; object-position: top;" %>
          <% end %>

          <h1 class="card-title mb-2">
            <%= link_to "#{person.first_name} #{person.last_name}", person_path(person) %>
          </h1>
         <p class="card-text mb-1">
            <%= person.party %>
          </p>
          <h5 class="card-text">
            <% if person.district %>
              <%= link_to person.district_title, district_path(person.district) %>
            <% else %>
              <%= person.district_title %>
            <% end %>
          </h5>

          <% if person.campaign_website.present? %>
            <p class="card-text">
              <% url = person.campaign_website.start_with?('http://', 'https://') ? person.campaign_website : "http://#{person.campaign_website}" %>
              <%= link_to url, url, target: "_blank", rel: "noopener noreferrer" %>
            </p>
          <% end %>


        </div>
      </div>
</div>
  </div>

app/views/shared/_search.html.erb
<%= search_form_for @q, url: search_people_path, html: { method: :get, class: 'd-flex' } do |f| %>
   <%= f.search_field :last_name_cont, placeholder: 'Search by Last Name', class: 'form-control', id: local_assigns[:search_input_id], 'data-dropdown-id': local_assigns[:dropdown_id] %>
<% end %>

<div id="<%= local_assigns[:dropdown_id] %>" class="autocomplete-dropdown"></div>

app/views/shared/_subscription_required.html.erb
<div>
    <h3>You must be subscribed to view this content.</h3>
    <br>
    <%= link_to 'Subscribe', '/pricing', :class => "btn btn-primary"%>
</div>

app/views/shared/_unsubscribe_link.html.erb
<p style="font-size: 14px; margin-top: 16px; Margin-top: 16px;">
  <%= link_to "Turn this notification off", unsubscribe_url(@user.unsubscribe_hash, subscription: subscription_type), style: "color: #bbbbbb;", target: :_blank %>
</p>

app/views/shared/_vacant.html.erb
<div class="card rounded primary-border flex-grow-1">
  <% if local_assigns[:show_header] %>
    <div class="card-header">
      <span>Incumbent</span>
    </div>
  <% end %>
  <div class="card-body text-center d-flex flex-column justify-content-center align-items-center">
    <%= image_tag 'blank-headshot.png', alt: 'vacant_headshot', class: "img-fluid rounded-circle mb-4", style: "width: 150px; height: 150px; object-fit: cover;" %>
    <h1 class="primary-blue">Vacant</h1>
  </div>
</div>