config/routes.rb
Rails.application.routes.draw do
  get 'contests/show'

  # Devise routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  # ActiveAdmin routes
  ActiveAdmin.routes(self)



  # Resource routes


  resources :campaign_finance_modules
  resources :candidate_committees do
    resources :reports
  end
  resources :candidates
  resources :former_offices
  resources :registration_snapshots do
    collection { post :import }
  end
  resources :statistical_data
  resources :historical_candidates
  resources :election_histories
  resources :updates
  
  resources :people do 
    resources :reports, only: [:index]
    
    member do
      get 'archive'
    end
  
    collection do
      get 'search'
    end
  end
  
  resources :campaigns
  resources :campaign_candidates
  resources :pricing, only: [:index]
  resources :reports
  resources :districts do
    member do
      get :follow
      get :unfollow
    end
    collection { post :import }
  end
  resources :jurisdictions do
    member do
      patch :toggle_archive
    end
  end
  resources :subscriptions
  resources :dashboard
  resources :help
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :users, only: [:index, :destroy]
  resources :blog_posts
  get 'tags/:tag_name', to: 'blog_posts#index', as: :filter_by_tag
  get 'navigate_jurisdiction', to: 'jurisdictions#navigate', as: :navigate_jurisdiction
  resources :elections, param: :slug do
    member do
      post 'process_results_update'
    end
    
    resources :election_updates
    resources :contests, only: [:show] do
      member do
        post 'pin', to: 'pinned_contests#create'
        delete 'unpin', to: 'pinned_contests#destroy'
      end
    end
    resources :uploads, only: [:create]
  end

  



  # Custom routes
  get 'emails/unsubscribe'
  get :search, controller: :main
  match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user

  # Root path
  root 'pages#home'

  # Additional information
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign_finance_module.rb
class CampaignFinanceModule < ApplicationRecord
  belongs_to :jurisdiction, optional: true
  belongs_to :district, optional: true


  def contribution_limit_output
    if self.contribution_limit == 0 || self.contribution_limit == nil
       "No Limit"
    else
       "$#{self.contribution_limit}"
    end
  end

  def corporate_contribution_output
    if self.corporate?
       "Allowed"
    else
       "Prohibited"
    end
  end

  def party_contribution_limit_output
   if self.party == true
    if self.party_limit == 0 || self.party_limit == nil
       "No Limit"
    else
         "$#{self.party_limit}"
    end
   else
      "Prohibited"
   end
  end

  def pac_contribution_output
    if self.pac?
       "Allowed"
    else
         "Prohibited"
    end
  end

end

app/controllers/campaign_finance_modules_controller.rb
class CampaignFinanceModulesController < ApplicationController
  before_action :set_campaign_finance_module, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin
  before_action :admin_mode

  # GET /campaign_finance_modules
  # GET /campaign_finance_modules.json
  def index
    @campaign_finance_modules = CampaignFinanceModule.all
  end

  # GET /campaign_finance_modules/1
  # GET /campaign_finance_modules/1.json
  def show
  end

  # GET /campaign_finance_modules/new
  def new
    @campaign_finance_module = CampaignFinanceModule.new
  end

  # GET /campaign_finance_modules/1/edit
  def edit
  end

  # POST /campaign_finance_modules
  # POST /campaign_finance_modules.json
  def create
    @campaign_finance_module = CampaignFinanceModule.new(campaign_finance_module_params)

    respond_to do |format|
      if @campaign_finance_module.save
        format.html { redirect_to @campaign_finance_module, notice: 'Campaign finance module was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_finance_module }
      else
        format.html { render :new }
        format.json { render json: @campaign_finance_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_finance_modules/1
  # PATCH/PUT /campaign_finance_modules/1.json
  def update
    respond_to do |format|
      if @campaign_finance_module.update(campaign_finance_module_params)
        format.html { redirect_to @campaign_finance_module, notice: 'Campaign finance module was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign_finance_module }
      else
        format.html { render :edit }
        format.json { render json: @campaign_finance_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_finance_modules/1
  # DELETE /campaign_finance_modules/1.json
  def destroy
    @campaign_finance_module.destroy
    respond_to do |format|
      format.html { redirect_to campaign_finance_modules_url, notice: 'Campaign finance module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_finance_module
      @campaign_finance_module = CampaignFinanceModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_finance_module_params
      params.require(:campaign_finance_module).permit(:corporate, :pac, :party, :contribution_limit, :party_limit, :district_id, :jurisdiction_id)
    end
end

app/helpers/campaign_finance_modules_helper.rb
module CampaignFinanceModulesHelper
end

app/views/campaign_finance_modules/_form.html.erb
<%= bootstrap_form_for(@campaign_finance_module, label_errors: true) do |f| %>
<% if @campaign_finance_module.errors.any? %>
    <% @campaign_finance_module.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md">
        <%= f.select(:jurisdiction_id, Jurisdiction.order(:name).all.collect { |v| [ v.name, v.id ] }, {:selected => params[:jurisdiction_id], :include_blank => true} ) %>
      </div>
      <div class="col-md">
        <%= f.select(:district_id, District.order(jurisdiction_id: :asc, name: :desc).all.collect { |v| ["#{v.jurisdiction.name} - #{v.name} (District #{v.district}) #{v.term_expires}", v.id ] }, {:selected => params[:district_id], :include_blank => true}) %>
      </div>
    </div>

    <div class="row my-3 text-center">
      <div class="col"><%= f.check_box :corporate, {:label => "Corporate Contributions Allowed"} %></div>
      <div class="col"><%= f.check_box :pac, {:label => "PAC Contributions Allowed"} %></div>
      <div class="col"><%= f.check_box :party, {:label => "Party Contributions Allowed"} %></div>
    </div>

    
    
    
    <div class="row">
      <div class="col">
        <%= f.number_field :contribution_limit %>
      </div>
      <div class="col">
        <%= f.number_field :party_limit %>
      </div>
    </div>
    
   
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/campaign_finance_modules/edit.html.erb
<h1>Editing Campaign Finance Module</h1>

<%= render 'form', campaign_finance_module: @campaign_finance_module %>

<%= link_to 'Show', @campaign_finance_module %> |
<%= link_to 'Back', campaign_finance_modules_path %>

app/views/campaign_finance_modules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaign Finance Modules</h1>

<table>
  <thead>
    <tr>
      <th>Corporate</th>
      <th>Pac</th>
      <th>Party</th>
      <th>Contribution limit</th>
      <th>Party limit</th>
      <th>Jurisdiction override</th>
      <th>Jurisdiction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_finance_modules.each do |campaign_finance_module| %>
      <tr>
        <td><%= campaign_finance_module.corporate %></td>
        <td><%= campaign_finance_module.pac %></td>
        <td><%= campaign_finance_module.party %></td>
        <td><%= campaign_finance_module.contribution_limit %></td>
        <td><%= campaign_finance_module.party_limit %></td>

        <td><%= campaign_finance_module.jurisdiction %></td>
        <td><%= link_to 'Show', campaign_finance_module %></td>
        <td><%= link_to 'Edit', edit_campaign_finance_module_path(campaign_finance_module) %></td>
        <td><%= link_to 'Destroy', campaign_finance_module, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign Finance Module', new_campaign_finance_module_path %>

app/views/campaign_finance_modules/new.html.erb
<h1>New Campaign Finance Module</h1>

<%= render 'form', campaign_finance_module: @campaign_finance_module %>

<%= link_to 'Back', campaign_finance_modules_path %>

app/views/campaign_finance_modules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Corporate:</strong>
  <%= @campaign_finance_module.corporate %>
</p>

<p>
  <strong>Pac:</strong>
  <%= @campaign_finance_module.pac %>
</p>

<p>
  <strong>Party:</strong>
  <%= @campaign_finance_module.party %>
</p>

<p>
  <strong>Contribution limit:</strong>
  <%= @campaign_finance_module.contribution_limit %>
</p>


<p>
  <strong>Party limit:</strong>
  <%= @campaign_finance_module.party_limit %>
</p>

<% if @campaign_finance_module.jurisdiction.present? %>
<p>
  <strong>Jurisdiction:</strong>
  <%= link_to "#{@campaign_finance_module.jurisdiction.name}", @campaign_finance_module.jurisdiction  %>
</p>
<%else%>
<p>
  <strong>District:</strong>
  <%= link_to "#{@campaign_finance_module.district.full_district_name}", @campaign_finance_module.district %>
</p>
<%end%>

<%= link_to 'Edit', edit_campaign_finance_module_path(@campaign_finance_module) %> |
<%= link_to 'Back', campaign_finance_modules_path %>