config/routes.rb
Rails.application.routes.draw do
  get 'contests/show'

  # Devise routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  # ActiveAdmin routes
  ActiveAdmin.routes(self)



  # Resource routes


  resources :campaign_finance_modules
  resources :candidate_committees do
    resources :reports
  end
  resources :candidates
  resources :former_offices
  resources :registration_snapshots do
    collection { post :import }
  end
  resources :statistical_data
  resources :historical_candidates
  resources :election_histories
  resources :updates
  
  resources :people do 
    resources :reports, only: [:index]
    
    member do
      get 'archive'
    end
  
    collection do
      get 'search'
    end
  end
  
  resources :campaigns
  resources :campaign_candidates
  resources :pricing, only: [:index]
  resources :reports
  resources :districts do
    member do
      get :follow
      get :unfollow
    end
    collection { post :import }
  end
  resources :jurisdictions do
    member do
      patch :toggle_archive
    end
  end
  resources :subscriptions
  resources :dashboard
  resources :help
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :users, only: [:index, :destroy]
  resources :blog_posts
  get 'tags/:tag_name', to: 'blog_posts#index', as: :filter_by_tag
  get 'navigate_jurisdiction', to: 'jurisdictions#navigate', as: :navigate_jurisdiction
  resources :elections, param: :slug do
    member do
      post 'process_results_update'
    end
    
    resources :election_updates
    resources :contests, only: [:show] do
      member do
        post 'pin', to: 'pinned_contests#create'
        delete 'unpin', to: 'pinned_contests#destroy'
      end
    end
    resources :uploads, only: [:create]
  end

  



  # Custom routes
  get 'emails/unsubscribe'
  get :search, controller: :main
  match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user

  # Root path
  root 'pages#home'

  # Additional information
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/update.rb
class Update < ApplicationRecord
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def update_params
      params.require(:update).permit(:message, :title)
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= simple_form_for(@update) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Updates</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.message %></td>
        <td><%= link_to 'Show', update %></td>
        <td><%= link_to 'Edit', edit_update_path(update) %></td>
        <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @update.message %>
</p>

<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>