config/routes.rb
Rails.application.routes.draw do
  get 'contests/show'

  # Devise routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: "registrations", confirmations: 'confirmations' }

  # ActiveAdmin routes
  ActiveAdmin.routes(self)



  # Resource routes


  resources :campaign_finance_modules
  resources :candidate_committees do
    resources :reports
  end
  resources :candidates
  resources :former_offices
  resources :registration_snapshots do
    collection { post :import }
  end
  resources :statistical_data
  resources :historical_candidates
  resources :election_histories
  resources :updates
  
  resources :people do 
    resources :reports, only: [:index]
    
    member do
      get 'archive'
    end
  
    collection do
      get 'search'
    end
  end
  
  resources :campaigns
  resources :campaign_candidates
  resources :pricing, only: [:index]
  resources :reports
  resources :districts do
    member do
      get :follow
      get :unfollow
    end
    collection { post :import }
  end
  resources :jurisdictions do
    member do
      patch :toggle_archive
    end
  end
  resources :subscriptions
  resources :dashboard
  resources :help
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :users, only: [:index, :destroy]
  resources :blog_posts
  get 'tags/:tag_name', to: 'blog_posts#index', as: :filter_by_tag
  get 'navigate_jurisdiction', to: 'jurisdictions#navigate', as: :navigate_jurisdiction
  resources :elections, param: :slug do
    member do
      post 'process_results_update'
    end
    
    resources :election_updates
    resources :contests, only: [:show] do
      member do
        post 'pin', to: 'pinned_contests#create'
        delete 'unpin', to: 'pinned_contests#destroy'
      end
    end
    resources :uploads, only: [:create]
  end

  



  # Custom routes
  get 'emails/unsubscribe'
  get :search, controller: :main
  match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all
  match 'users/:id' => 'users#destroy', via: :delete, as: :admin_destroy_user

  # Root path
  root 'pages#home'

  # Additional information
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :candidate_committee, optional: true
  delegate :district, to: :person
  delegate :jurisdiction, to: :person
  delegate :incumbent_district, to: :person
  belongs_to :person, optional: true
  cattr_accessor :current_user


  mount_uploader :pdf, ReportUploader

  def net_coh
    current_coh - current_debt
  end

  def top_fundraiser
    Report.order('period_receipts').limit(3)
  end

  def most_recent_filing_period_start
    most_recent = Date.new(2020,1,19)
  end

  def burn_rate
    period_disbursements / period_receipts
  end

  def total_expenditures
    transactions.where(transaction_type: "EXPN").sum(:amount)
end

  def current_period
    if period_begin == most_recent_filing_period_start
      return true
    end
  end

  def report_name

      "#{self.period_begin} - #{self.period_end} Report for #{self.candidate_committee.name}"

  end

  scope :with_election, -> { where("candidate.candidate_committee.reports > 0") }

  def gop_reports
    republicans = Person.all.where(party: "Republican")     
    gop_reports = []    
    republicans.each do |republican|       
      if republican.reports.present?         
        gop_reports << republican.reports.each.period_receipts 
      end 
    end
  end

=begin   
  def district_followers
    district_followers = []
    if self.district.at_large_district == false
      self.district.followers.each do |follower|
      district_followers << follower
      end
    elsif self.district.at_large_district == true
      self.district.jurisdiction.districts.each do |district|
        district.followers.each do |follower|
        district_followers << follower
        end
      end
    end
    return district_followers
  end
=end



  private



  



end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # before_action :is_subscriber?
  before_action :authorize_admin, except: [:index, :show]
  before_action :admin_mode, except: [:index, :show]

  # GET /reports
  # GET /reports.json
  def index
    if params[:person_id]
      @reports = Person.find(params[:person_id]).reports
    else
      @reports = Report.all
    end
    
    set_meta_tags title: 'Campaign Finance Reports',
    site: 'The Ballot Book'
  end



  # GET /reports/1
  # GET /reports/1.json
  def show
    set_meta_tags title: @report.report_name,
    site: 'The Ballot Book'
  end

  # GET /reports/new
  def new
    @report = Report.new

    set_meta_tags title: "New Report",
                site: 'The Ballot Book'
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
    set_meta_tags title: "Edit Report",
                site: 'The Ballot Book'
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        if @report.person.present?
          @report.district_followers.uniq.each do |user|
            if user.notify_when_new_report? && user.subscribed?
              ReportMailer.with(user: user, report: @report).tracked_report.deliver
            end
          end
        end
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @candidate_committee = @report.candidate_committee
    @report.destroy
    respond_to do |format|
      format.html { redirect_to candidate_committee_url(@candidate_committee), notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected

  def person
    @person ||=
      if params[:incumbent_id]
        Incumbent.find(params[:incumbent_id])
      elsif params[:candidate_id]
        Candidate.find(params[:candidate_id])
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(
        :period_begin, 
        :period_end, 
        :report_filed, 
        :period_monetary_receipts, 
        :period_nonmonetary_receipts, 
        :period_receipts,
        :period_disbursements, 
        :current_coh, 
        :current_debt, 
        :loans_received, 
        :pdf,
        :is_amended, 
        :candidate_committee_id
      )
    end

    def is_subscriber?
      redirect_to '/pricing', notice: "You must be subscribed to access this page!" unless current_user.subscribed? 
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="container bg-white shadow-sm border rounded mt-2">
  <%= bootstrap_form_for(@report, label_errors: true) do |f| %>

    <div class="row p-3">
      <div class="col-md-3">
        <h5 class="heavy">Report Details</h5>
      </div>
      <div class="col-md-9">
        <div class="row mb-3">
        <div class="col-md-6">
          <% if f.object.new_record? && Report.last %>
            <%= f.date_field :period_begin, value: Report.last.period_begin, required: true %>
            <%= f.date_field :period_end, value: Report.last.period_end, required: true %>
          <% else %>
            <%= f.date_field :period_begin, value: f.object.period_begin, required: true %>
            <%= f.date_field :period_end, value: f.object.period_end, required: true %>
          <% end %>
        </div>

          <div class="col-md-6">
            <%= f.date_field :report_filed, required: true, value: (f.object.new_record? ? Date.today.strftime("%Y-%m-%d") : f.object.report_filed) %> 
          </div>
        </div>
        <hr>
        <div class="row mb-3">
          <div class="col-md-6 border-right">
            <%= f.number_field :period_monetary_receipts, step: :any, required: true, label: "Monetary Receipts" %>
            <%= f.number_field :loans_received, step: :any, label: "Loans Received", required: true %>
            <%= f.number_field :period_nonmonetary_receipts, step: :any, required: true, label: "Nonmonetary Receipts" %>
            <%= f.number_field :period_receipts, step: :any, required: true, label: "Total Receipts" %>
          </div>
          <div class="col-md-6">
            <%= f.number_field :period_disbursements, step: :any, required: true, label: "Disbursements" %>
            <%= f.number_field :current_coh, step: :any, label: "Cash on Hand", required: true %>
            <%= f.number_field :current_debt, step: :any, label: "Debt", required: true %>
          </div>  
        </div>
        <hr>
        <div class="row mb-3">
          <div class="col-md-12">
            <%= f.select(:candidate_committee_id, 
                        CandidateCommittee.order('name ASC').map { |v| [ "#{v.person.last_name}, #{v.person.first_name} - #{v.name}", v.id ] }, 
                        { selected: params[:candidate_committee_id], include_blank: true }, 
                        label: "Candidate Committee:" ) %>            
            <%= f.check_box :is_amended, label: "Report is Amended" %>
            <%= f.file_field :pdf, { label: "Upload Report" } %>
          </div>
        </div>
      </div>
    </div>

    <div class="row p-3">
      <div class="col-md-12 text-center">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'Back', reports_path, class: "btn btn-outline-primary"  %>
      </div>
    </div>

  <% end %>
</div>

app/views/reports/_top_fundraisers.html.erb
<% unless params[:person_id] %>  
    <div class="col-lg-6">
        <div class="card shadow-sm mb-3 bg-white rounded primary-border" style="max-width: 100%;">
          <div class="card-header">
              Top Candidate Fundraisers<br> (Period Ending October 17, 2020)
          </div>
          <div class="table-responsive p-1">
            <table class="table table p-2 bg-white " style="width:100%">           
                  <thead class="thead-light">
                    <tr>
                      <th></th>
                      <th>Candidate<br></th>
                      <th>Period Receipts</th>
                    </tr>
                  </thead>
                  <% Report.where("candidate_report = ? AND period_end = ?", true, Date.new(2020,10,17)).order(period_receipts: :DESC).limit(14).each do |report|  %>
                  
                  <tbody>
                    <tr>
                      <td class="condensed-column text-center"><%if report.person.image.present?%><%= image_tag report.person.image.url(:headshot), alt: 'headshot', :class => "avatar shadow-sm", size: "45x45"  %><%end%></td>
                      <td><% if report.person.running_reelection? %><%= link_to "#{report.person.first_name} #{report.person.last_name}", report.person  %><br><small><%= report.person.incumbent_district.name %>
                      <%else%><%= link_to "#{report.person.first_name} #{report.person.last_name}", report.person  %><br><small><%= report.person.district.name %><%end%></td>
                      <td><span class="float-end green-pill"><%= number_to_currency(report.period_receipts) %></span></td>
                    
                    <tr>
                    <%end%>
                  </tbody>
                  
            </table>
          </div>
        </div>
    </div>
    
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3 bg-white rounded primary-border" style="max-width: 100%;">
        <div class="card-header">
            Most-Funded Committees<br> (Period Ending October 17, 2020)
        </div>
        <div class="table-responsive p-1">
          <table class="table table p-2 bg-white" style="width:100%">           
                <thead class="thead-light">
                  <tr>
                    <th>Committee<br></th>
                    <th>COH</th>
                  </tr>
                </thead>
                <% Report.where("period_end = ?", Date.new(2020,10,17)).where("committee_id IS NOT NULL").order(current_coh: :DESC).limit(10).each do |report|  %>
                <tbody>
                  <tr>
                    <% if report.committee.present? %>
                    <td><%= link_to "#{report.committee.name}", report.committee  %><br><small><%= report.committee.jurisdiction.name %></td>
                    <td><span class="float-end green-pill">$<%= number_with_delimiter(report.current_coh, :delimiter => ',') %></span></td>
                    <%end%>
                  <tr>
                  <%end%>
                </tbody>
          </table>
        </div>
      </div>
  </div>
  <%end%>

app/views/reports/edit.html.erb
<%= render 'form', report: @report %>

app/views/reports/index.html.erb
<div class="container">

    <div class="row">
      <h3 class="primary-blue heavy m-4">Latest Campaign Finance Reports</h3>
      
    </div>


    <div class="row">
                     <!--PUT TOP FUNDRAISERS HERE -->
    </div>  
    





<br>
<div class="panel panel-default">
  <div class="table-responsive shadow bg-white rounded primary-border p-4">
    <table class="table table-sm" id="reports">
      <thead class="thead-light">
        <tr>
          <th>Name<br></th>
          <th>Start Date</th>
          <th>End Date</th>
          <th class="text-right">Receipts</th>
          <th class="text-right">Expenses</th>
          <th class="text-right">Cash on Hand</th>
          <th>View</th>
        </tr>
      </thead>

      <tbody>
        <% Report.where('created_at >= ?', Date.yesterday).order('created_at DESC').each do |report| %>
          
          <tr>
            
            <td class=""><%= link_to "#{report.committee.name}", report.committee  %></small><%if current_user.admin?%> - <%= link_to 'Edit', edit_report_path(report) %><%end%><br>
                </td>
            <td class=""><%= "#{report.period_begin.strftime("%b-%d-%y")}" %></td>
            <td><%= "#{report.period_end.strftime("%b-%d-%y")}" %></td>
            <td class=""><span class="float-end green-text"><%= number_to_currency(report.period_receipts) %></span></td>
            <td class=""><span class="float-end red-text"><%= number_to_currency(report.period_disbursements) %></span></td>
            <td class=""><%if report.net_coh < 0 %><span class="float-end gop-text">(<%= number_to_currency(report.net_coh) %>)</span><%else%><span class="float-end"><%= number_to_currency(report.net_coh) %></span><%end%></td>
            <td class><% if report.pdf.url.present? %><%= link_to "View", report.pdf.url, :class => "btn btn-primary", target: :_blank %><%end%></td>
          </tr>
          
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
<br>
<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Report', new_report_path, :class => "btn btn-primary mr-2" %>
<%end%>
<% if params[:person_id] %>
<%= link_to "Back to #{Person.find(params[:person_id]).full_name}", Person.find(params[:person_id]), :class => "btn btn-primary mr-2" %>
<%end%>
</div>
<script>
    $( document ).on('turbolinks:load', function() {
    $('#reports').DataTable( {
      retrieve: true, 
      "order": [[ 1, "desc" ]]
    });
});
</script>

app/views/reports/new.html.erb
<%= render 'form', report: @report %>

app/views/reports/show.html.erb
<div class="container bg-white shadow-sm rounded primary-border p-4">

  <div class="row">
  
<div class="col-auto">
  Report Filer:<br>
  Report Filed:<br>
  Period Begin:<br>
  Period End:<br>
  <hr>
  Monetary Receipts:<br>
  Non-Monetary Receipts:<br>
  Loans Received:<br>
  Total Receipts:<br>
  <hr>
  Period Disbursements:<br>
  Cash-On-Hand:<br>
  Outstanding Debt:<br>
</div>
<div class="col-auto">
  <% if @report.candidate_committee.present? %>
    <%= link_to @report.candidate_committee.name, @report.candidate_committee %> 
    (<%= link_to @report.candidate_committee.person.full_name, @report.candidate_committee.person %>)
    <br>
  <% end %>
  <%= @report.report_filed.to_formatted_s(:long) %>
  <% if @report.is_amended? %> (Amended)<% end %>
  <br>
  <%= @report.period_begin.to_formatted_s(:long) %><br>
  <%= @report.period_end.to_formatted_s(:long) %>
  <hr>
  $<%= number_with_delimiter(@report.period_monetary_receipts, delimiter: ',') %><br>
  $<%= number_with_delimiter(@report.period_nonmonetary_receipts, delimiter: ',') %><br>
  $<% if @report.loans_received.present? %>
    <%= number_with_delimiter(@report.loans_received, delimiter: ',') %>
  <% else %>0.00<% end %>
  <br>
  $<%= number_with_delimiter(@report.period_receipts, delimiter: ',') %><br>
  <hr>
  $<%= number_with_delimiter(@report.period_disbursements, delimiter: ',') %><br>
  $<%= number_with_delimiter(@report.current_coh, delimiter: ',') %><br>
  $<%= number_with_delimiter(@report.current_debt, delimiter: ',') %>
  <br>
  <% if @report.pdf.url.present? %>
    <%= link_to "Download Report", @report.pdf.url, target: "_blank", rel: "noopener noreferrer" %>
  <% end %>
</div>






  </div>
<br>




<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Delete Report', @report, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</div>

<script>

jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "currency-pre": function ( a ) {
        a = (a==="-") ? 0 : a.replace( /[^\d\-\.]/g, "" );
        return parseFloat( a );
    },
 
    "currency-asc": function ( a, b ) {
        return a - b;
    },
 
    "currency-desc": function ( a, b ) {
        return b - a;
    }
} );

$(document).ready(function () {
    $('table.display').DataTable({
        order: [[2, 'desc']],
        columnDefs: [
       { type: 'currency', targets: 2 }
     ],
    });
});
</script>